### ISSUE TITLE
Concatenated Age Mostly NA

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#10]
Warren created the variable d_117249500 that gives age derived from DOB at time of user profile completion in the participants table. However, this is missing for a large majority of participants. Can you review the code for this variable? I need the age of participants for filtering purposes.

**Comment by jacobmpeters** [comment]
I looked into this and it seems to be unrelated to the query itself. d_117249500 is definitely missing for many participants in the Connect.participants even though d_371067537 is available. I'm don't think I'm in a position to help with this issue.

**Comment by KELSEYDOWLING7** [comment]
It's a concatenated variable created from the DOB variables (month, day, year of DOB). I don't know if that helps

**Comment by jacobmpeters** [comment]
I don't work with any code that is upstream of the participants table. This seems like it might be a dev/ops issue rather than a query/flattening issue.

**Comment by KELSEYDOWLING7** [comment]
Nicole advised I open this in Episphere instead and have Tony take a look at it.
