### ISSUE TITLE
Missing biospecimens variables in dev [10/19/2022] - Jing

### ISSUE THREAD

**Issue by jacobmpeters** [Analyticsphere/flatteningRequests#11]
Compared with the Connect biospecimens data (original one), the flat version are missing these variables shown attached (especially those with compound field path in the sheet). Please help me double check if possible. 

https://nih-my.sharepoint.com/:x:/g/personal/wuj12_nih_gov/ERt22Nj0IUZGvHsfHpeGCCABX3-5lUYTgSfo4Aba1stT0g

**Comment by jeannewu** [comment]
Yes. Just these variables need to help us carry to the flat version from dev.Connect.Biospecimens table. Thanks, Jake.

**Comment by jacobmpeters** [comment]
- I added all variables from the excel sheet with type INT64 or STRING to the flatBiospecimen_JP table in dev. 
- I did not think that it is appropriate to add those variables with type STRUCT. 
- The query that generates this table can be found under _Saved Queries --> Project Queries --> flatBiospecimen_JP_ in dev.
- There is currently no scheduled query for this table in any of the environments. @FrogGirl1123 @jeannewu please let me know if you would like me to add one.

**Comment by jeannewu** [comment]
Hi, Jake, thank you very much for letting me know. Yes, no need to ferry those struct variables to the flat table. Thanks for letting me know.
