### ISSUE TITLE
Missing Module 4 DEV variables

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#20]
Variables missing in FlatConnect.module4_v1_JP that have responses in testing (a majority of these varibales were just recently added to the module):

D_869829679
D_736086261
D_294308065
D_385583361
D_768802173
D_150560299
D_122054737
D_948492967
D_805353966
D_512143997
D_982650994
D_945794974
D_663869343
D_320166033_D_452103273
D_275978701
D_195803565
D_282326355
D_141249692
D_494968690
D_270024672_D_665593888

**Comment by jacobmpeters** [comment]
Hi Kelsey,

I added the variables to the FlatConnect.module4_v1_JP table in dev.

I did not see D_270024672_D_665593888 in the Connect.module4_v1 table, but I did find D_665593888.D_665593888, so I added it instead. 

Let me know if I that is the correct variable or if I am misunderstanding something.

**Comment by KELSEYDOWLING7** [comment]
I'm sorry I thought I added this one too as missing:

D_509553290_D_298170847

**Comment by jacobmpeters** [comment]
No worries! I just added that one in too!

**Comment by KELSEYDOWLING7** [comment]
Thanks! I have two more scenarios to go through so I'll add those missing variables down here in the comments section as I go

**Comment by KELSEYDOWLING7** [comment]
Also missing:

D_845483079
D_270024672_D_665593888

**Comment by jacobmpeters** [comment]
Hi Kelsey,

I used one of my new tricks to add all new variables present in the Connect.module4_v1 table to the FlatConnect.module4_v1_JP table automatically. So hopefully all the data that you need will be there.

**Comment by KELSEYDOWLING7** [comment]
D_270024672_D_665593888 is still missing. But everything else is in there!

**Comment by jacobmpeters** [comment]
Great! D_270024672_D_665593888 should be there now. I'll keep looking out for requests :)

**Comment by KELSEYDOWLING7** [comment]
Thanks, it's in there but null for all participants. At least 3 participants answered this question

**Comment by jacobmpeters** [comment]
Hi Kelsey, There is no D_270024672.D_665593888 variable in the Connect.module4_v1 table in dev, so it makes sense that it is not populating in FlatConnect.module4_v1_JP. There is a D_665593888.D_665593888 though.. Is this what you need?

**Comment by KELSEYDOWLING7** [comment]
Ohh ok I got confused when you said it should be in there now. But D_665593888.D_665593888 I can see and it is populating data. I'm wondering if that's the same type of problem Daniel is trying to fix now, since that doesn't follow the data dictionary
