### ISSUE TITLE
Missing Variables from M1 in DEV

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#21]
In FlatConnect.module1_v2_JP, these variables are missing and were answered in testing:

test3_11_29$D_750420077_D_582784267 
test3_11_29$D_750420077_D_700100953 
test3_11_29$D_750420077_D_751402477

**Comment by jacobmpeters** [comment]
I added these variables to the FlatConnect.module1_v2_JP dev. The table/query is up to date. I'll keep monitoring this issue.

**Comment by KELSEYDOWLING7** [comment]
Thanks! These too:

D_527057404_D_206625031
D_259397450_D_206625031
D_684692228_D_261863326
D_195363361_1_1_D_261863326_1_1
D_247160067_1_1_D_261863326_1_1
D_900939817_1_1_D_261863326_1_1
D_938150507_1_1_D_206625031_1_1
D_601211723_1_1_D_206625031_1_1
D_861788020_1_1_D_206625031_1_1
D_204425387_1_1_D_206625031_1_1
D_558929585_1_1_D_206625031_1_1
D_233764880_1_1_D_261863326_1_1
D_700374192_D_700374192_D_580409149
