### ISSUE TITLE
Mod2 DEV variable issues

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#22]
FlatConnect.module2_v2_JP in DEV:

This variable is populating NA. It should be 0 for no and 1 for yes. All other variables in this table are populating 0 or 1
D_643361372_D_535003378

These variables are all populating NA. It should be 0 for no and 1 for yes. 
D_543780863_D_543780863_D_441493408 
D_543780863_D_543780863_D_612012325 
D_543780863_D_543780863_D_100752105
D_543780863_D_543780863_D_207913198 
D_543780863_D_543780863_D_863920008
D_543780863_D_543780863_D_787142499
D_543780863_D_543780863_D_205223932
D_543780863_D_543780863_D_817131019
D_543780863_D_543780863_D_807835037
D_543780863_D_543780863_D_684201296
D_543780863_D_543780863_D_535003378

**Comment by jacobmpeters** [comment]
Hi Kelsey, 

It looks like these are in the flattened table correctly:

D_543780863_D_441493408,
D_543780863_D_207913198,
D_543780863_D_100752105,
D_543780863_D_535003378,
D_543780863_D_612012325,

But the ones that you listed that start with "D_543780863_D_543780863.." are not in the Connect.module2_v2 table at all. It's possible that they should be listed with just a single "D_543780863" at the beginning. If so, I can correct this in the query. Let me know what you think? Hopefully this makes sense...

**Comment by KELSEYDOWLING7** [comment]
Great! The single nested variables have the data in them. 

Is it possible to remove the double nested variables here that don't populate data?

**Comment by jacobmpeters** [comment]
Yep! I removed the double nested ones.
