### ISSUE TITLE
Module 1 Stage Variables Missing 

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#24]
Missing from nih-nci-dceg-connect-stg-5519.FlatConnect.module1_v2_JP:

D_750420077_D_582784267
D_750420077_D_751402477
D_750420077_D_700100953

**Comment by jacobmpeters** [comment]
Thanks, Kelsey! I've added these variables to all three environments.

 "D_750420077": [
  582784267,
  751402477,
  700100953,
  846483618,
  505282171,
  578416151
 ]

**Comment by KELSEYDOWLING7** [comment]
Great thanks!!

**Comment by jacobmpeters** [comment]
Ahh.. Thanks for letting me know that they aren't showing up. Looks like I added them for the wrong module! I'll fix it.. and confirm..

**Comment by jacobmpeters** [comment]
Ok. I think I fixed this issue. Let me know how it looks tomorrow :)

**Comment by KELSEYDOWLING7** [comment]
Yup! They're in there and populating data
