### ISSUE TITLE
Module4 variables missing in stage

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#26]
Variables in source table but not flattened table:

- D_845483079
- D_736086261
- D_294308065
- D_385583361
- D_768802173
- D_150560299
- D_122054737
- D_948492967
- D_805353966
- D_512143997
- D_982650994
- D_945794974
- D_663869343
- D_320166033.D_452103273
- D_275978701
- D_195803565
- D_282326355
- D_509553290.D_298170847
- D_141249692
- D_494968690
- D_805353966

Null in the flattened table, answer in source table, and has different CID in the flattened table than the source table:
- D_728155643_D_867247249 in flattened table, D_728155643_D_728155643 in source table
- D_380621340_D_867247249 in flattened table, D_380621340_D_380621340 in source table
- D_999694720_D_867247249 in flattened table, D_999694720_D_999694720 in source table
- D_849066624_D_867247249 in flattened table, D_849066624_D_849066624 in source table
- D_425315696_D_867247249 in flattened table, D_425315696_D_425315696 in source table
- D_529608184_D_867247249 in flattened table, D_529608184_D_529608184 in source table
-  D_234731641_D_867247249 in flattened table, D_234731641_D_234731641 in source table
-  D_664561394_D_867247249 in flattened table, D_664561394_D_664561394 in source table
- D_450154625_D_867247249 in flattened table, D_450154625_D_450154625 in source table
-  D_812161236_D_867247249 in flattened table, D_812161236_D_812161236 in source table
- D_964437163_D_867247249 in flattened table, D_964437163_D_964437163 in source table
- D_975198123_D_489075623 in flattened table, D_975198123_D_975198123 in source table
- D_778495585_D_489075623 in flattened table,  D_778495585_D_778495585 in source table
- D_829751791_D_489075623 in flattened table,  D_829751791_D_829751791 in source table
- D_914325712_D_489075623 in flattened table,  D_914325712_D_914325712 in source table
- D_682457230_D_489075623 in flattened table,  D_682457230_D_682457230 in source table
- D_404118353_D_489075623 in flattened table,  D_404118353_D_404118353 in source table
- D_806530984_D_489075623 in flattened table,  D_806530984_D_806530984 in source table
- D_613251957_D_489075623 in flattened table,  D_613251957_D_613251957 in source table
- D_288109261_D_489075623 in flattened table,  D_288109261_D_288109261 in source table
- D_437395872_D_489075623 in flattened table,  D_437395872_D_437395872 in source table
- D_860269869_D_451310566 in flattened table,  D_860269869_D_860269869 in source table
- D_928112898_D_451310566 in flattened table,  D_928112898_D_928112898 in source table
- D_412195193_D_451310566 in flattened table,  D_412195193_D_412195193 in source table
- D_750000285_D_451310566 in flattened table,  D_750000285_D_750000285 in source table
- D_849979952_D_451310566 in flattened table,  D_849979952_D_849979952 in source table
- D_552298163_D_451310566 in flattened table,  D_552298163_D_552298163 in source table
- D_710443293_D_451310566 in flattened table,  D_710443293_D_710443293 in source table
- D_709755471_D_451310566 in flattened table,  D_709755471_D_709755471 in source table
- D_701803756_D_451310566 in flattened table,  D_701803756_D_701803756 in source table
- D_878144094_D_451310566 in flattened table,  D_878144094_D_878144094 in source table

**Comment by jacobmpeters** [comment]
I'll work on this issue this morning. Thank you, Kelsey.

**Comment by jacobmpeters** [comment]
Variables to check:
- [ ] D_845483079
- [ ] D_736086261
- [ ] D_294308065
- [ ] D_385583361
- [ ] D_768802173
- [ ] D_150560299
- [ ] D_122054737
- [ ] D_948492967
- [ ] D_805353966
- [ ] D_512143997
- [ ] D_982650994
- [ ] D_945794974
- [ ] D_663869343
- [ ] D_320166033.D_452103273
- [ ] D_275978701
- [ ] D_195803565
- [ ] D_282326355
- [ ] D_509553290.D_298170847
- [ ] D_141249692
- [ ] D_494968690
- [ ] D_805353966

**Comment by jacobmpeters** [comment]
Issues to check:
- [ ] D_728155643_D_867247249 in flattened table, D_728155643_D_728155643 in source table
- [ ] D_380621340_D_867247249 in flattened table, D_380621340_D_380621340 in source table
- [ ] D_999694720_D_867247249 in flattened table, D_999694720_D_999694720 in source table
- [ ] D_849066624_D_867247249 in flattened table, D_849066624_D_849066624 in source table
- [ ] D_425315696_D_867247249 in flattened table, D_425315696_D_425315696 in source table
- [ ] D_529608184_D_867247249 in flattened table, D_529608184_D_529608184 in source table
- [ ] D_234731641_D_867247249 in flattened table, D_234731641_D_234731641 in source table
- [ ] D_664561394_D_867247249 in flattened table, D_664561394_D_664561394 in source table
- [ ] D_450154625_D_867247249 in flattened table, D_450154625_D_450154625 in source table
- [ ] D_812161236_D_867247249 in flattened table, D_812161236_D_812161236 in source table
- [ ] D_964437163_D_867247249 in flattened table, D_964437163_D_964437163 in source table
- [ ] D_975198123_D_489075623 in flattened table, D_975198123_D_975198123 in source table
- [ ] D_778495585_D_489075623 in flattened table, D_778495585_D_778495585 in source table
- [ ] D_829751791_D_489075623 in flattened table, D_829751791_D_829751791 in source table
- [ ] D_914325712_D_489075623 in flattened table, D_914325712_D_914325712 in source table
- [ ] D_682457230_D_489075623 in flattened table, D_682457230_D_682457230 in source table
- [ ] D_404118353_D_489075623 in flattened table, D_404118353_D_404118353 in source table
- [ ] D_806530984_D_489075623 in flattened table, D_806530984_D_806530984 in source table
- [ ] D_613251957_D_489075623 in flattened table, D_613251957_D_613251957 in source table
- [ ] D_288109261_D_489075623 in flattened table, D_288109261_D_288109261 in source table
- [ ] D_437395872_D_489075623 in flattened table, D_437395872_D_437395872 in source table
- [ ] D_860269869_D_451310566 in flattened table, D_860269869_D_860269869 in source table
- [ ] D_928112898_D_451310566 in flattened table, D_928112898_D_928112898 in source table
- [ ] D_412195193_D_451310566 in flattened table, D_412195193_D_412195193 in source table
- [ ] D_750000285_D_451310566 in flattened table, D_750000285_D_750000285 in source table
- [ ] D_849979952_D_451310566 in flattened table, D_849979952_D_849979952 in source table
- [ ] D_552298163_D_451310566 in flattened table, D_552298163_D_552298163 in source table
- [ ] D_710443293_D_451310566 in flattened table, D_710443293_D_710443293 in source table
- [ ] D_709755471_D_451310566 in flattened table, D_709755471_D_709755471 in source table
- [ ] D_701803756_D_451310566 in flattened table, D_701803756_D_701803756 in source table
- [ ] D_878144094_D_451310566 in flattened table, D_878144094_D_878144094 in source table

**Comment by jacobmpeters** [comment]
For issues like `D_728155643_D_867247249 in flattened table, D_728155643_D_728155643 in source table`, 
would you like me to remove D_728155643_D_867247249 from the query?

D_728155643_D_728155643 is "REAPETED", so its response becomes "D_728155643_D_728155643_D_678602069". Is this what you are expecting?

**Comment by jacobmpeters** [comment]
Variables be removed from query:

- [ ]  D_728155643_D_867247249
- [ ]  D_380621340_D_867247249 
- [ ]  D_999694720_D_867247249
- [ ]  D_849066624_D_867247249 
- [ ]  D_425315696_D_867247249
- [ ]  D_529608184_D_867247249 
- [ ]  D_234731641_D_867247249 
- [ ]  D_664561394_D_867247249 
- [ ]  D_450154625_D_867247249 
- [ ]  D_812161236_D_867247249 
- [ ]  D_964437163_D_867247249
- [ ]  D_975198123_D_489075623 
- [ ]  D_778495585_D_489075623 
- [ ]  D_829751791_D_489075623 
- [ ]  D_914325712_D_489075623 
- [ ]  D_682457230_D_489075623 
- [ ]  D_404118353_D_489075623 
- [ ]  D_806530984_D_489075623 
- [ ]  D_288109261_D_489075623
- [ ]  D_437395872_D_489075623
- [ ]  D_860269869_D_451310566
- [ ]  D_928112898_D_451310566
- [ ]  D_412195193_D_451310566
- [ ]  D_750000285_D_451310566
- [ ]  D_849979952_D_451310566
- [ ]  D_552298163_D_451310566
- [ ]  D_710443293_D_451310566
- [ ]  D_709755471_D_451310566
- [ ]  D_701803756_D_451310566
- [ ]  D_878144094_D_451310566

**Comment by KELSEYDOWLING7** [comment]
> For issues like `D_728155643_D_867247249 in flattened table, D_728155643_D_728155643 in source table`, would you like me to remove D_728155643_D_867247249 from the query?
> 
> D_728155643_D_728155643 is "REPEATED", so its response is in a JSON array and is therefor flattened as "D_728155643_D_728155643_D_678602069". Is this what you are expecting?

Yes! Exactly. That's how the previous flattened table displayed the variable CIDs

**Comment by jacobmpeters** [comment]
Thanks, Kelsey. I updated the query/table in stage and I believe these issues are resolved. Let me know if things look ok on your end.

**Comment by KELSEYDOWLING7** [comment]
These look great! I'm able to see all the responses now. There are some duplicates in the flattened table though that don't have the necessary double nested CID. Would you be able to delete those as well? They don't have any data in them

- D_412195193_D_232063618
- D_701803756_D_232063618
- D_849979952_D_232063618
- D_860269869_D_232063618
- D_928112898_D_232063618
- D_232063618
- D_552298163_D_232063618
- D_709755471_D_232063618
- D_710443293_D_232063618
- D_750000285_D_232063618
- D_878144094_D_232063618

Thank you!

**Comment by jacobmpeters** [comment]
Sure! I removed that list of CIDs and updated the query/table in dev, stg and prod. 

Let me know if you need anything else or feel free to close this issue if things look good :)

**Comment by KELSEYDOWLING7** [comment]
Thanks! The last of her data came in over the weekend. It looks like just a few more variables need to be added to the flattened table (data is in the source table):
- D_710443293_D_451310566
- D_709755471_D_451310566

**Comment by jacobmpeters** [comment]
Ok! Those have been added. Let me know if you see them.

**Comment by KELSEYDOWLING7** [comment]
Yup! They're all there
