### ISSUE TITLE
FlatConnect.bioSurvey_v1_JP

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#28]
When you get a chance, can you please add D_959877599_D_908044428 to this table? Right now only D_959877599_D_700620868 is in the flattened table

**Comment by jacobmpeters** [comment]
I updated my code to include that variable and ran the query, so the table should be correct for now. But for some reason BigQuery Scheduled Queries cannot be updated right now. Seems to be an issue on Google's end. I'll try to update the query again in the morning.

**Comment by jacobmpeters** [comment]
I just deleted the old query and scheduled a new one with the same name as a workaround. Let me know if you have any more issues.
