### ISSUE TITLE
Mod 2: variable with no data in either version

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#31]
d_668834883 variables are both nested and double nested in mod2 both version 1 & 2. 

But these single nested variables have no data.  Could you delete those?
D_668834883_D_246843973, D_668834883_D_515434780, D_668834883_D_535003378,  D_668834883_D_674148137, D_668834883_D_807835037, D_668834883_D_854184254

Only the double nested variable, D_668834883_D_668834883_D_640559281, has no data but the single nested variable, D_668834883_D_640559281, does. This makes sense as it's an open text response.  Can you delete D_668834883_D_668834883_D_640559281?

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Version 2 seems to have the fix but version 1 does not

**Comment by jacobmpeters** [comment]
Ok. Thanks for checking. I will look into this today.

**Comment by jacobmpeters** [comment]
It looks like the scheduled query for FlatConnect.module2_v1_JP failed to run due to a syntax error. I resolved the issue and the data now look good to me. Let me know if it looks good to you.

**Comment by KELSEYDOWLING7** [comment]
Yes, now it's fixed. Thank you!
