### ISSUE TITLE
d_928693120 "urine accession id" is now appearing as 3-field object rather than integer

### ISSUE THREAD

**Issue by jacobmpeters** [Analyticsphere/flatteningRequests#32]
From @KELSEYDOWLING7:

Good morning! I have a question about one of the variables. d_928693120 was working fine as just the numeric portion of the string in the FlatConnect.biospecimen_JP file for the past few weeks. Now all of a sudden then data is coming out like.

{integer:2304805473,string:null,provided:integer}

Can you take a look at that?

**Comment by KELSEYDOWLING7** [comment]
Yes that worked. Thank you!

**Comment by jacobmpeters** [comment]
@anthonypetersen 

We have noticed a data structure change for a “Dashboard clinical urine accession ID” variable (CID: 928693120) in the Connect.biospecimen table in PROD that is causing issues for our flattening code and reporting.
 
The variable used to show up as single value in BQ like this:
 
"d_928693120": 12314404245
 
But now it is appearing as an JSON object or BQ RECORD:
 
"d_928693120": {
    "integer": "12314404245",
    "string": null,
    "provided": "integer"
   }
 
Do you know why this might have occurred? We anticipated some accession IDs appearing as arrays, but we were not expecting them to be objects like this. It’s possible it has to do with the move from transfer from Firestore to BQ..

**Comment by jacobmpeters** [comment]
This issue was resolved by the DevOps team.
