### ISSUE TITLE
Module 1 Unflattened age responses 

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#48]
Hi Jake, I was looking at this week's automated QC rules and noticed a new set of issues with mom, dad, sibling, and child age responses for module 1 version 1. I'm not sure why/how/if the older responses for a module no longer available have changed. If you look at lines 21-152 here https://nih.app.box.com/file/1474903479636 you'll see that the responses , [958239616], 178420302, [178420302], or [] have been replaced with  {D_178420300:0,D_958239600:0} or {D_178420300:0:0}

**Comment by jacobmpeters** [comment]
Thanks for letting me know. This definitely seems like a flattening bug. I'll look into this and get back to you

**Comment by KELSEYDOWLING7** [comment]
Thanks!

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 I've resolved this issue. There were some variables that were incorrectly listed in the `module1_v1-variables.csv` file. I corrected this, re-flattened the table and generated a new [QC Report](https://nih.app.box.com/file/1475750452773) and those issues no longer pop up.
