### ISSUE TITLE
Delete mother variables from M2 queries [9/29/22] - Jing, Kelsey

### ISSUE THREAD

**Issue by jacobmpeters** [Analyticsphere/flatteningRequests#5]
Switch to generating M2V2 and M2V1 queries from single set of input files 
- [x] Be sure to programmatically add _V2 tag for V2 using string find/replace functions 
- [x] Update scheduled queries **DONE**
- [x] Notify Jing and Kelsey when done **DONE**

**Comment by KELSEYDOWLING7** [comment]
Hi Jake, I'm not sure if this falls under this request, but it looks like this variable D_745268907_D_399982309_D_535003378 is not pulling any data. 

It should have 2305 responses (0 for no or 1 for yes) as all these other linked variables:
(D_745268907_D_399982309_D_194424439, D_745268907_D_399982309_D_221645137, D_745268907_D_399982309_D_422188606, D_745268907_D_399982309_D_469512398, D_745268907_D_399982309_D_535003378, D_745268907_D_399982309_D_555555502, D_745268907_D_399982309_D_800410166, D_745268907_D_399982309_D_974248369)

**Comment by jacobmpeters** [comment]
Hi @KELSEYDOWLING7 , I added the variables that you requested to M1V1 and M1V2. Both tables should be up-to-date as of Nov. 9 in prod. I will not update dev and stg because those are about to change. However, it would be useful if you could let me know if I resolved the issue in prod. 

commit: https://github.com/Analyticsphere/flatteningRequests/commit/e7afac05336e4d48ba69fc68770aabe5d4705e2a

**Comment by jacobmpeters** [comment]
Hi Kelsey, I added it to the wrong table. I'll correct it and get back to you.

**Comment by jacobmpeters** [comment]
> Hi Jake, should that comment have been for the module 1 request? Or is that regarding module 2? The variables above are still showing as null. These three variables are also still missing (in the participants table):
> D_745268907_D_198719822
> D_745268907_D_767785846
> D_745268907_D_893965588_D_893965588

Ok, I added those variables to the M2 table and removed them from M1V1 and M1V2. Can you please check again when you are able?

**Comment by KELSEYDOWLING7** [comment]
Update to previous comment:


> Hi Jake, should that comment have been for the module 1 request? Or is that regarding module 2? The variables above are still showing as null. As are these variables:
D_745268907_D_442059084_D_690018400
D_745268907_D_517976064_D_181769837, D_745268907_D_517976064_D_182827107, D_745268907_D_517976064_D_203192394, D_745268907_D_517976064_D_261267696, D_745268907_D_517976064_D_345916806, D_745268907_D_517976064_D_371531887, D_745268907_D_517976064_D_420058896, D_745268907_D_517976064_D_423631576, D_745268907_D_517976064_D_535003378, D_745268907_D_517976064_D_619501806, D_745268907_D_517976064_D_734860227, D_745268907_D_517976064_D_760484278, D_745268907_D_517976064_D_868685663, D_745268907_D_517976064_D_904954920, D_745268907_D_517976064_D_926584500, D_745268907_D_517976064_D_936042582



>These variables are also missing (in the participants table):
 D_745268907_D_198719822
D_745268907_D_767785846
D_745268907_D_893965588_D_893965588
D_745268907_D_881200765_D_881200765_D_441493408
D_745268907_D_881200765_D_881200765_D_612012325
D_745268907_D_881200765_D_881200765_D_100752105
D_745268907_D_881200765_D_881200765_D_207913198
D_745268907_D_881200765_D_881200765_D_863920008
D_745268907_D_881200765_D_881200765_D_787142499
D_745268907_D_881200765_D_881200765_D_205223932
 D_745268907_D_881200765_D_881200765_D_817131019
D_745268907_D_881200765_D_881200765_D_807835037
D_745268907_D_881200765_D_881200765_D_535003378

**Comment by jacobmpeters** [comment]
Hi @KELSEYDOWLING7, 
I added all of the variables that you said were missing in the previous comment with commit 708bc7f and updated the queries/tables in dev/stg/prod.

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Great, thank you! Were you able to take a look as that variables pulling no data as well?

**Comment by jacobmpeters** [comment]
Hi Kelsey, 

Yes, I did look into that. All of the variables that are present in the participants table are now in the queries. I did take some notes on those variables that were not pulling data (as you listed them above). I check their presence/absence in the participants table for version 1 and version 2. My notes are below.

D_745268907.D_442059084 --> NOT in Connect.participants
D_745268907.D_517976064 --> in Connect.participants 
D_745268907.D_517976064 --> in Connect.participants
D_745268907.D_204421360 --> in Connect.participants
D_745268907_V2.D_894610280 --> in Connect.participants for V2 only
D_745268907_V2.D_222110888 --> in Connect.participants for V2 only
D_745268907.D_371748514 --> NOT in Connect.participants
D_745268907.D_858525957 --> NOT in Connect.participants
D_745268907.V2.D_900299856 --> in Connect.participants for V2 only
D_745268907.D_187772368 --> NOT in Connect.participants
D_745268907.D_198719822 --> NOT in Connect.participants
D_745268907.D_767785846 --> NOT in Connect.participants
D_745268907_D_893965588_D_893965588 --> NOT in Connect.participants
