### ISSUE TITLE
covid19Survey_v1: one non-existing variables and newly answered variables 

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#51]
Hi Jake, in covid19Survey_v1_JP  there's a variable D_715581797_V2_1_1 but that doesn't exist in the raw table and it has no data. Can we delete?

These variables were recently responded to, so they're in the raw table but not the flattened. Can we reflatten it to add them?
D_980800222_7_7 
D_498462481_6_6 
D_498462481_7_7 
D_744230001_4_4 
D_782396371_4_4
D_930944000_4_4
D_984121390_4_4
D_179406442_4_4 
D_893966847_4_4 
D_169509213_2_2

**Comment by jacobmpeters** [comment]
Thanks for making this issue, Kelsey. I'll take care of these today and get back to you when done :)

**Comment by jacobmpeters** [comment]
Hi @KELSEYDOWLING7 . This should be taken care of. The query should include all new variables and D_715581797_V2_1_1 has been removed.
