### ISSUE TITLE
Weird occurrence in research bioSurvey_JP table

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#53]
The variable D_479143504_D_203919683 is only showing values of 0 or null in the flattened table but there's plenty of instances of it in the raw table. That's never been a problem in past runs and there's 8077 instances in this afternoon BUM report. So there should be instances of D_479143504_D_203919683 =1

(SQL code for reference:
SELECT D_479143504_D_203919683 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1_JP` 
group by D_479143504_D_203919683)

**Comment by KELSEYDOWLING7** [comment]
In checking this morning, I see this is actually an issue with every D_479143504 variable. 

It is also happening with all D_406270109, D_899251483 (V1 and V2), D_542661394 variables.  Essentially every select all that apply in the Mouthwash section of the survey

**Comment by jacobmpeters** [comment]
Thanks, Kelsey. I'll look into this this morning.

**Comment by jacobmpeters** [comment]
Thanks for letting me know that that table is also affected. I'll keep investigating and let you know when I learn more.

**Comment by jacobmpeters** [comment]
Note to self:

#### Values of D_479143504_D_203919683 in `FlatConnect.bioSurvey_v1_JP`
```sql
SELECT D_479143504_D_203919683 
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1_JP`
GROUP BY D_479143504_D_203919683;
```
Results:
- 0
- null

#### Values of D_479143504 in `Connect.bioSurvey_v1`
```sql
SELECT DISTINCT responses 
FROM `nih-nci-dceg-connect-prod-6d04.Connect.bioSurvey_v1`,
UNNEST(D_479143504) AS responses;
```
Results:
- 203919683
- 807884576
- 165596977
- 390351864
- 578402172
- 184513726

#### Counts of each response given in `Connect.bioSurvey_v1_JP`
```sql
SELECT response, COUNT(*) AS resp_count
FROM `nih-nci-dceg-connect-prod-6d04.Connect.bioSurvey_v1`,
UNNEST(D_479143504) AS response
GROUP BY response
```
| response | resp_count |
|---|---|
| 203919683 | 8124 |
| 807884576 | 6697 |
| 165596977 | 957 |
| 390351864 | 4482 |
| 578402172 | 835 |
| 184513726 | 457 |

> We would expect D_479143504_D_203919683 to have 8124 1's in `FlatConnect.bioSurvey_v1_JP`, but it contains only 0's and nulls.

**Comment by jacobmpeters** [comment]
They should all be refreshed!

**Comment by KELSEYDOWLING7** [comment]
I'm having other issues running the report but from the flattened tables it looks good! These all have values of 1 now as expected. I think we're good to close this issue

**Comment by jacobmpeters** [comment]
Ok. Thank you, Kelsey. Let me know if you need help with the other issues you're having.
