### ISSUE TITLE
Flattening Mouthwash and KitAssembly Tables

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#55]
Hi @jacobmpeters , it looks like we now have data in the mouthwash and kit assembly tables. Can you flatten those whenever you get a chance? Also just a heads up, we're expecting a bunch of new variables to be answered in the participants table this week. I'm hoping tomorrow will contain most of them but I'm not sure what time they'll be coming in so we may need to refresh the tables a few times this week for new variables.

**Comment by jacobmpeters** [comment]
I will try to get to that asap, Kelsey. Thank you for notifying me. I'll let you know when it's done and I can help you refresh it as needed afterwards.

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 They should be up-to-date. Let me know if anything else comes up.

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Thanks! I'll check now

**Comment by KELSEYDOWLING7** [comment]
It looks like there's still some variables in the raw participants table that aren't in the flattened table. Do you mind rerunning if you have time? If it helps, these are the variables I'm looking for:
d_173836415.d_266600170.d_319972665.d_379252329
d_173836415.d_266600170.d_319972665.d_221592017
d_173836415.d_266600170.d_319972665.d_661940160
d_195145666

**Comment by jacobmpeters** [comment]
sure! I didn't touch the participants table at all, so I can do that now...

**Comment by KELSEYDOWLING7** [comment]
Ah! Ok that makes sense then. I'm seeing everything I expected for the KitAssembly and MW tables

**Comment by jacobmpeters** [comment]
Ok! I updated the participants table too. Let me know if you see what you need

**Comment by KELSEYDOWLING7** [comment]
Yes, looks like everything's there and Erin confirmed some nesting updates from the recent testing. Thanks!
