### ISSUE TITLE
New variable in module 3

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#58]
Hi Jake, no rush but when you get a chance can you reflatten module 3 in prod? there's a newly answered question d_784119588. It's in the raw table. I tried rerunning the flattening code but it didn't seem to apply the change

**Comment by jacobmpeters** [comment]
Hi Kelsey. I tried to run my flattening code and it broke for `module3`. These mixed type variables are breaking our flattening pipeline:
```
"D_633553324.entity.D_602102163","NULLABLE","STRING"
"D_633553324.entity.D_164707243","NULLABLE","STRING"
"D_633553324.entity.D_818310825","NULLABLE","STRING"
"D_633553324.entity.D_175385712","NULLABLE","STRING"
"D_633553324.entity.D_772143730","NULLABLE","STRING"
"D_633553324.entity.D_843593800","NULLABLE","STRING"
"D_633553324.entity.D_294629316","NULLABLE","STRING"
"D_633553324.entity.D_771426895","NULLABLE","STRING"
"D_470862706.entity.D_690918725","REPEATED","STRING"
"D_470862706.entity.D_178609656","REPEATED","STRING"
"D_470862706.entity.D_261957180","REPEATED","STRING"
"D_470862706.entity.D_688123102","REPEATED","STRING"
"D_470862706.entity.D_356133766","REPEATED","STRING"
"D_470862706.entity.D_715827646","REPEATED","STRING"
"D_470862706.entity.D_643512687","REPEATED","STRING"
"D_470862706.entity.D_912659087","REPEATED","STRING"
```
Are the variables you are interested nested under `633553324` or `470862706`?

**Comment by KELSEYDOWLING7** [comment]
Interesting. No, that variable should only be the unnested d_784119588 as it is in the flattened tables

**Comment by jacobmpeters** [comment]
Ok. I added that one in manually. Can you let me know if it looks ok on your end?

**Comment by KELSEYDOWLING7** [comment]
Yes!! That worked, thank you

**Comment by jacobmpeters** [comment]
Great!

**Comment by KELSEYDOWLING7** [comment]
So sorry! @jacobmpeters  Could you do the same for the MW table?

**Comment by jacobmpeters** [comment]
MW has been updated!
