### ISSUE TITLE
Biospecimen Table Concept ID Duplicate 

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#60]
Hi Jake, it looks like somehow a second version of this variable ended up in the flattened biospecimen table and its causing a discrepancy issue in the output files. Is it possible to delete d_143615646_d_260133861? That variable has no data in it at all. the variable that's needed is just d_260133861

Thanks!

![image](https://github.com/user-attachments/assets/8dad7ea6-285b-4be8-92d4-ec4e093e7140)

**Comment by jacobmpeters** [comment]
That variable has been removed!
