### ISSUE TITLE
Connect Experience Table and its variables in the Participants Table

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#61]
Hi Jake! When you get a chance can you flatten the experience2024 table in prod? It now has data in the raw table.

Also can you update the participants table? Theirs a few new variables; I'm not sure if you need them specifically identified but just in case:
d_199471989
d_956490759
d_263355177

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 Thanks for making the issue. I'll do this now..

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 This should be good-to-go. I just ran the flattening for the experience survey in prod and updated the scheduled query for the participants table. It is running now and may need an hour to complete.

Let me know if you see what you need

**Comment by KELSEYDOWLING7** [comment]
Looks good thanks!
