### ISSUE TITLE
Add missing variable to Module 4 [10/6/22] - Kelsey

### ISSUE THREAD

**Issue by jacobmpeters** [Analyticsphere/flatteningRequests#8]
D_264797252_D_264797252 (only answer of 178420302)

**Comment by jacobmpeters** [comment]
I added D_264797252_D_264797252 to the input files. I'll wait to hear what the other missing variables are before I update the query in BQ.

**Comment by KELSEYDOWLING7** [comment]
D_219317801_D_533003859 was the other variable I found missing. I'm going to run through Module 4 one more time today to make sure nothing else is missing

**Comment by jacobmpeters** [comment]
I added D_219317801_D_533003859 to the input files.

**Comment by KELSEYDOWLING7** [comment]
Missing:
 D_812161236_D_943813942
D_505863509_D_441314504
D_250486386_D_224594497
D_957717014_D_984805254
D_726654963_D_276249147
D_279093430_D_476938134
D_279093430_D_561635035
D_279093430_D_134210521
D_279093430_D_715370929
D_279093430_D_109991481
D_279093430_D_494380686
D_279093430_D_440796912
D_657986901_D_657986901
D_509526051_D_509526051
D_143927994_D_119483547
D_143927994_D_194338739
D_143927994_D_387077376
D_143927994_D_113352592
D_143927994_D_768114466
D_143927994_D_938180781
D_564684946_D_148846635
D_564684946_D_192663941
D_564684946_D_245044197
D_370121390_D_580185896
D_370121390_D_599607007
D_935378391_D_785588454
D_935378391_D_419659205
D_935378391_D_653181757
D_935378391_D_733619119
D_935378391_D_843680322
D_935378391_D_716343828
D_320166033_D_275244758
D_320166033_D_688216428
D_320166033_D_843674851
D_320166033_D_570311888
D_320166033_D_557852952
D_320166033_D_970217879
D_383535171_D_666445636
D_383535171_D_398622449
D_383535171_D_521925072
D_383535171_D_888514303
D_383535171_D_905002640
D_383535171_D_687407917
D_133566757_D_199489170
D_133566757_D_605155921
D_133566757_D_300476868
D_133566757_D_384403974
D_133566757_D_585153023
D_133566757_D_248996395
D_509553290_D_295693777
D_509553290_D_646099557
D_509553290_D_886284650
D_509553290_D_367684056
D_509553290_D_389478638
D_509553290_D_949478044
D_239279719_D_143093472
D_239279719_D_746619983
D_239279719_D_911964974
D_239279719_D_711881258
D_239279719_D_390941579
D_239279719_D_737885885
D_778711683_D_117703279
D_778711683_D_734790700
D_778711683_D_278164536
D_778711683_D_160188014
D_778711683_D_596751155
D_778711683_D_624226136
D_778495585_D_314198277
D_778495585_D_489075623
D_928112898_D_451310566
D_928112898_D_232063618
D_829751791_D_314198277
D_829751791_D_489075623
D_412195193_D_451310566
D_412195193_D_232063618
D_914325712_D_314198277
D_914325712_D_489075623
D_750000285_D_451310566
D_750000285_D_232063618
D_682457230_D_314198277
D_682457230_D_489075623
D_849979952_D_451310566
D_849979952_D_232063618
D_404118353_D_314198277
D_404118353_D_489075623
D_552298163_D_451310566
D_552298163_D_232063618
D_806530984_D_314198277
D_806530984_D_489075623
D_710443293_D_451310566
D_710443293_D_232063618
D_613251957_D_314198277
D_613251957_D_489075623
D_878144094_D_451310566
D_878144094_D_232063618
D_437395872_D_314198277
D_437395872_D_489075623
D_709755471_D_451310566
D_709755471_D_232063618
D_288109261_D_314198277
D_288109261_D_489075623
D_701803756_D_451310566
D_701803756_D_232063618
D_598478268_D_670605457
D_823509509_D_971016509
D_771505558_D_771505558
D_771505558_D_184681822
D_149476435_D_708136662
D_867096017_D_340877879
D_264797252_D_264797252
D_263588196_D_583500714
D_291959537
D_668887646_D_668887646
D_219317801_D_533003859



Home addresses 5-11 haven't been answered often, so I wasn't originally reviewing them, but they should be added. 

Right now there's a variable D_212343294 that should be: 
D_212343294_D_445867902
D_212343294_D_348049244
D_212343294_D_684217044
D_212343294_D_600319581
D_212343294_D_212343294

D_298296694 that should be: 
D_298296694_D_915527263
D_298296694_D_325919807
D_298296694_D_298296694

D_120942783 should be :
D_120942783_D_120942783

D_752015272_D_752015272 should be:
D_752015272_D_139208251


All 12 questions with the child concept ID 867247249 pull no data. This is probably not likely. Do you mind taking a look? It should be 0 for no and 1 for yes for the response.


D_270024672_D_665593888 and D_665593888_D_665593888 are both in the flattened data. Only D_270024672_D_665593888 is in the data dictionary but has no data, D_665593888_D_665593888 is not in the data dictionary but is showing as responded by all

**Comment by jacobmpeters** [comment]
Thank you for the detailed notes. I'll work through this and reach out with questions.

**Comment by jacobmpeters** [comment]
> Missing: D_812161236_D_943813942 D_505863509_D_441314504 D_250486386_D_224594497 D_957717014_D_984805254 D_726654963_D_276249147 D_279093430_D_476938134 D_279093430_D_561635035 D_279093430_D_134210521 D_279093430_D_715370929 D_279093430_D_109991481 D_279093430_D_494380686 D_279093430_D_440796912 D_657986901_D_657986901 D_509526051_D_509526051 D_143927994_D_119483547 D_143927994_D_194338739 D_143927994_D_387077376 D_143927994_D_113352592 D_143927994_D_768114466 D_143927994_D_938180781 D_564684946_D_148846635 D_564684946_D_192663941 D_564684946_D_245044197 D_370121390_D_580185896 D_370121390_D_599607007 D_935378391_D_785588454 D_935378391_D_419659205 D_935378391_D_653181757 D_935378391_D_733619119 D_935378391_D_843680322 D_935378391_D_716343828 D_320166033_D_275244758 D_320166033_D_688216428 D_320166033_D_843674851 D_320166033_D_570311888 D_320166033_D_557852952 D_320166033_D_970217879 D_383535171_D_666445636 D_383535171_D_398622449 D_383535171_D_521925072 D_383535171_D_888514303 D_383535171_D_905002640 D_383535171_D_687407917 D_133566757_D_199489170 D_133566757_D_605155921 D_133566757_D_300476868 D_133566757_D_384403974 D_133566757_D_585153023 D_133566757_D_248996395 D_509553290_D_295693777 D_509553290_D_646099557 D_509553290_D_886284650 D_509553290_D_367684056 D_509553290_D_389478638 D_509553290_D_949478044 D_239279719_D_143093472 D_239279719_D_746619983 D_239279719_D_911964974 D_239279719_D_711881258 D_239279719_D_390941579 D_239279719_D_737885885 D_778711683_D_117703279 D_778711683_D_734790700 D_778711683_D_278164536 D_778711683_D_160188014 D_778711683_D_596751155 D_778711683_D_624226136 D_778495585_D_314198277 D_778495585_D_489075623 D_928112898_D_451310566 D_928112898_D_232063618 D_829751791_D_314198277 D_829751791_D_489075623 D_412195193_D_451310566 D_412195193_D_232063618 D_914325712_D_314198277 D_914325712_D_489075623 D_750000285_D_451310566 D_750000285_D_232063618 D_682457230_D_314198277 D_682457230_D_489075623 D_849979952_D_451310566 D_849979952_D_232063618 D_404118353_D_314198277 D_404118353_D_489075623 D_552298163_D_451310566 D_552298163_D_232063618 D_806530984_D_314198277 D_806530984_D_489075623 D_710443293_D_451310566 D_710443293_D_232063618 D_613251957_D_314198277 D_613251957_D_489075623 D_878144094_D_451310566 D_878144094_D_232063618 D_437395872_D_314198277 D_437395872_D_489075623 D_709755471_D_451310566 D_709755471_D_232063618 D_288109261_D_314198277 D_288109261_D_489075623 D_701803756_D_451310566 D_701803756_D_232063618 D_598478268_D_670605457 D_823509509_D_971016509 D_771505558_D_771505558 D_771505558_D_184681822 D_149476435_D_708136662 D_867096017_D_340877879 D_264797252_D_264797252 D_263588196_D_583500714 D_291959537 D_668887646_D_668887646 D_219317801_D_533003859
> 
> Home addresses 5-11 haven't been answered often, so I wasn't originally reviewing them, but they should be added.
> 
> Right now there's a variable D_212343294 that should be: D_212343294_D_445867902 D_212343294_D_348049244 D_212343294_D_684217044 D_212343294_D_600319581 D_212343294_D_212343294
> 
> D_298296694 that should be: D_298296694_D_915527263 D_298296694_D_325919807 D_298296694_D_298296694
> 
> D_120942783 should be : D_120942783_D_120942783
> 
> D_752015272_D_752015272 should be: D_752015272_D_139208251
> 
> All 12 questions with the child concept ID 867247249 pull no data. This is probably not likely. Do you mind taking a look? It should be 0 for no and 1 for yes for the response.
> 
> D_270024672_D_665593888 and D_665593888_D_665593888 are both in the flattened data. Only D_270024672_D_665593888 is in the data dictionary but has no data, D_665593888_D_665593888 is not in the data dictionary but is showing as responded by all

Thank you for the detailed notes. I'll work through this and reach out with questions.

**Comment by KELSEYDOWLING7** [comment]
Of course! As I mentioned a majority of these missing variables may not have been answered as of yet, but wanted to make a record of them early on. Thank you!

**Comment by jacobmpeters** [comment]
I added the list of Missing variables to the M2-variables.csv file. I will work on the other tasks on Thursday.

**Comment by KELSEYDOWLING7** [comment]
You added these variables to M2? Or  M4?

**Comment by KELSEYDOWLING7** [comment]
Are these in the query and prod table now to check?

**Comment by jacobmpeters** [comment]
> Are these in the query and prod table now to check?

They are not in the query and prod table yet.. I'm working more on this now. I'll update what I have by end of day.

**Comment by jacobmpeters** [comment]
I just updated the flatM4_JP_SA table and scheduled query in prod with the variable additions and removals that you requested.

The CID 867247249 does not appear at all in the Connect.participants table.

D_270024672_D_665593888 does not appear in the Connect.participants table. Would you like me to remove it from the query?

**Comment by KELSEYDOWLING7** [comment]
867247249 not being in the participants table is a little concerning but I'll look into that. It looks like in the participants table the main concept ID repeats itself, though that doesn't match the data dictionary. For example, D_716117817.D_728155643.D_728155643 in the participants table is D_716117817.D_728155643.D_867247249 in the data dictionary.

Childhood home 2 was removed from the survey so D_270024672_D_665593888 can be removed

**Comment by KELSEYDOWLING7** [comment]
D_170035952_D_674785575

**Comment by jacobmpeters** [comment]
Hi Kelsey, 

I went through all of these Secondary Question CIDs and queried all of the Question Text CIDs that were present in the Connect.participants table in prod. The only one for which there was response of ["678602069"] was D_716117817.D_728155643.D_728155643. I did not see any that ended with D_867247249. 

This is the query that I ran in BigQuery:

```
SELECT
  D_716117817.D_728155643.D_728155643,
  D_716117817.D_728155643.D_943813942,
  D_716117817.D_380621340.D_380621340,
  D_716117817.D_380621340.D_943813942,
  D_716117817.D_999694720.D_999694720,
  D_716117817.D_999694720.D_943813942,
  D_716117817.D_849066624.D_849066624,
  D_716117817.D_849066624.D_943813942,
  D_716117817.D_425315696.D_425315696,
  D_716117817.D_425315696.D_943813942,
  D_716117817.D_529608184.D_943813942,
  D_716117817.D_234731641.D_943813942,
  D_716117817.D_664561394.D_943813942,
  D_716117817.D_450154625.D_943813942,
  D_716117817.D_812161236.D_943813942,
  D_716117817.D_964437163.D_943813942,
  D_716117817.D_170035952.D_170035952,
FROM
  `nih-nci-dceg-connect-prod-6d04.Connect.participants`
WHERE
  ( D_716117817.D_728155643.D_728155643 IS NOT NULL
    OR D_716117817.D_728155643.D_943813942 IS NOT NULL
    OR D_716117817.D_380621340.D_380621340 IS NOT NULL
    OR D_716117817.D_380621340.D_943813942 IS NOT NULL
    OR D_716117817.D_999694720.D_999694720 IS NOT NULL
    OR D_716117817.D_999694720.D_943813942 IS NOT NULL
    OR D_716117817.D_849066624.D_849066624 IS NOT NULL
    OR D_716117817.D_849066624.D_943813942 IS NOT NULL
    OR D_716117817.D_425315696.D_425315696 IS NOT NULL
    OR D_716117817.D_425315696.D_943813942 IS NOT NULL
    OR D_716117817.D_529608184.D_943813942 IS NOT NULL
    OR D_716117817.D_234731641.D_943813942 IS NOT NULL
    OR D_716117817.D_664561394.D_943813942 IS NOT NULL
    OR D_716117817.D_450154625.D_943813942 IS NOT NULL
    OR D_716117817.D_812161236.D_943813942 IS NOT NULL
    OR D_716117817.D_964437163.D_943813942 IS NOT NULL
    OR D_716117817.D_170035952.D_170035952 IS NOT NULL )
```

D_170035952_D_674785575 is not in the participants table in any form, but I will add it to the M4 query as D_716117817_D_170035952_D_674785575 so that it will appear once there is data for this variable. 

Please let me know what you would like me to do for the variables in the query above. It is hard to know how to include them in the M4 query when neither the Data Dictionary nor the Connect.participants table are a reliable reference.

**Comment by KELSEYDOWLING7** [comment]
Thanks! That does make sense, as most people will be listing their current address first so it's more likely that only that question will get an answer of still live there

**Comment by jacobmpeters** [comment]
I updated the scheduled queries in all 3 tiers. The tables should be up to date Oct. 27.
